phim/urls.py
from django.urls import path, include
from phim.views.account.register_view import UserRegisterView


from phim.views.account.logout_view import UserLogoutView
from phim.views.account.login_view import UserLoginView
from phim.views.film.actor_view import ActorListView
from phim.views.film.movie_view import MovieListView
from phim.views.film.movie_view import MovieListView1
from phim.views.film.movie_view import PhimBoListView
from phim.views.film.movie_view import PhimLeListView
from phim.views.film.movie_view import MovieDetailView
from phim.views.account.user_view import ProfileUserView
from phim.views.film.get_api_model_movie import update_movie
from phim.views.film.get_data_movie import update_movie1
from phim.views.film.movie_search_view import SearchResultView

app_name = "phim"

urlpatterns = [ 
    # account/login/
    path(
        route='login/',
        view=UserLoginView.as_view(),
        name='login'
    ),

    # account/login/
    path(
        route='register/',
        view=UserRegisterView.as_view(),
        name='register'
    ),
    path("update_movie/", update_movie, name="update_movie"),
    path("update_movie1/", update_movie1, name="update_movie"),
    #API google
    # path('accounts/', include('allauth.urls')),

    # account/logout/
    path(
        route='logout/',
        view=UserLogoutView.as_view(),
        name='logout'
    ),
    #category-phim/<str:slug>/
    path(
        route='category/<str:slug>/phim',
        view=MovieListView.as_view(),
        name='category_phim'
    ),

    #home
    path(
        route='',
        view=MovieListView.as_view(),
        name='home'
    ),

    #actor
    path(
        route='actor/',
        view=ActorListView.as_view(),
        name='actor'
    ),

    #phim
    path(
        route='movie/',
        view=MovieListView1.as_view(),
        name='movie'
    ),

    path(
        route='movie/series',
        view=PhimBoListView.as_view(),
        name='series'

    ), 

    path(
        route='movie/film',
        view=PhimLeListView.as_view(),
        name='film'

    ), 

    path(
        route='movie/<str:slug>/',
        view=MovieDetailView.as_view(),
        name='phimdetail'

    ),

    #user
    path(
        route='user/profile',
        view=ProfileUserView.as_view(),
        name='user_profile'

    ),
    path(
        route='search/', 
        view=SearchResultView.as_view(),
        name='search'
        )


    
]

phimhayho/urls.py
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static, serve
from django.contrib import admin
from django.urls import include, path, re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('phim.urls', namespace='phim')),  
  

]

phim/models/Users.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


#Thông tin Users
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #img
    address = models.CharField(max_length=100, help_text="Địa chỉ")
    email = models.BooleanField(default=False)
    created_on = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.user.username}'s Profile"
    

phim/models/actor.py
from django.db import models
from django.utils import timezone


#Ung dung thu 3
from cloudinary.models import CloudinaryField

#model dien vien
class Actor(models.Model):

    #Gioi tinh
    MALE = "Nam"
    FAMELE = "Nữ"
    LGBT = "LGBT"

    #Lua Chon
    STATUS_CHOICES = (
        (MALE, 'Nam'),
        (FAMELE, 'Nữ'),
        (LGBT, 'LGBT'),
    )

    name = models.CharField(max_length=100)
    sex = models.CharField(max_length=10, choices=STATUS_CHOICES, default='')
    info = models.TextField()
    birth = models.DateField()
    flyer = CloudinaryField('Fyler')

    class Meta:
        unique_together = ("name",)
        verbose_name = 'actor'
        verbose_name_plural = 'actores'

    def __str__(self):
        return self.name

phim/models/ads_model.py
from django.db import models
#
from cloudinary.models import CloudinaryField

class Ads (models.Model):

    name = models.CharField(max_length=100)
    img = CloudinaryField('img')
    
    def __str__(self):
        return self.name

phim/models/category_model.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

class Category(models.Model):

    name = models.CharField(max_length=100, null=False, blank=False)
    slug = models.SlugField()
 
    class Meta:
        unique_together = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('phim:category_movies',
                       kwargs={'slug': self.slug})
    

phim/models/comment_model.py
from django.db import models
from django.utils import timezone

from phim.models.Users import User

class Comment(models.Model):

    name = models.ForeignKey(User, on_detele=models.CASCADE, related_name='comments')
    comment = models.TextField(null = False, blank=True)
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Nhận xét của {self.name}"

phim/models/movie_model.py
from django.db import models
import uuid
from django.urls import reverse
from phim.models.category_model import Category
from django.utils.text import slugify
from django.utils import timezone
from django.db.models import Q


from phim.models.actor import Actor
#Ung dung T3
from taggit.managers import TaggableManager
from cloudinary.models import CloudinaryField
from taggit.managers import TaggableManager

#Search
from taggit.models import Tag
from phim.models.category_model import Category
from django.db.models import Count

#model phim
class Movie(models.Model):

    #trang thai phim
    DRAFTED = "RAW"
    FULLHD = "FULLHD"
    COMINGSOON = "COMINGSOON"

    #lua chon
    STATUS_CHOICES = (
        (DRAFTED, 'RAW'),
        (FULLHD, 'FULLHD'),
        (COMINGSOON,'COMINGSOON'),
    )

    title:str=models.CharField(max_length=225)
    title_el =models.CharField(max_length=250)
    rating = models.CharField(max_length=10)
    description:str=models.TextField()
    created =models.DateTimeField(auto_now_add=True)
    uuid=models.UUIDField(default=uuid.uuid4,unique=True)
    country = models.CharField(max_length=100)
    slug = models.SlugField()
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,
                              default='FULLHD')
    views = models.PositiveIntegerField(default=0)
    time = models.CharField(max_length=100)
 
    
    trailer = models.CharField(max_length=400)
    category = models.ManyToManyField(Category,
                                 related_name='movies')
    movies = models.CharField(max_length=500)
    date_published = models.DateTimeField(null=True, blank=True,
                                          default=timezone.now)
    year = models.CharField(max_length=4)
    flyer=CloudinaryField('img', transformation=[{'width': 400, 'height': 600, 'crop': 'fill'}])
    stars = models.ManyToManyField(Actor, related_name='movies')
    tags = TaggableManager(blank=True)

    class Meta:
        unique_together = ("title",)
        verbose_name = 'movie'
        verbose_name_plural = 'movies'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super(Movie, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('phim:phimdetail',
                       kwargs={'slug': self.slug})


class MovieSearch:
    @staticmethod
    def search_movies(filters):
        query = filters.get('query', None)
        category = filters.get('category', None)
        tags = filters.get('tags', None)
        year = filters.get('year', None)

        qs = Movie.objects.all()

        if query:
            query_lookups = (Q(title__icontains=query) | Q(description__icontains=query) | Q(tags__name__icontains=query))
            qs = qs.filter(query_lookups).distinct()

        if category:
            qs = qs.filter(category__name__icontains=category)

        if tags:
            qs = qs.filter(tags__name__in=tags)

        if year:
            qs = qs.filter(year=year)

        return qs

    @staticmethod
    def get_filters(request):
        filters = {}
        query = request.GET.get('query')
        category = request.GET.get('category')
        tags = request.GET.getlist('tags')
        year = request.GET.get('year')

        if query is not None:
            filters['query'] = query.strip()

        if category is not None:
            filters['category'] = category.strip()

        if tags is not None:
            filters['tags'] = [tag.strip() for tag in tags if tag.strip()]

        if year is not None:
            filters['year'] = year.strip()

        return filters

    @staticmethod
    def get_categories():
        return Category.objects.all()

    @staticmethod
    def get_tags():
        return Tag.objects.all()

    @staticmethod
    def get_years():
        return [year for year in range(timezone.now().year, 1900, -1)]
    
    @staticmethod
    def get_countries():
        return Movie.objects.values('country').annotate(count=Count('country')).order_by('-count')

phim/api/views/category_views.py
from rest_framework import generics

from phim.models.category_model import Category
from ..serializers.category_serializers import CategorySerializer

class CategoryList(generics.ListAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

phim/templates/phim_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="no-js">

<head>
	<!-- Basic need -->
	<title>Xem Hay Ho |{% block title %} {% endblock title %}</title>
	<link rel="icon" href="{% static 'images/logo_home3.png' %}">
	<meta charset="UTF-8">
	<meta name="description" content="">
	<meta name="keywords" content="XemHayHo">
	<meta name="author" content="NguyenDucNgoc">
	<link rel="profile" href="#">

    <!--Google Font-->
    <link rel="stylesheet" href='http://fonts.googleapis.com/css?family=Dosis:400,700,500|Nunito:300,400,600' />
	<!-- Mobile specific meta -->
	<meta name=viewport content="width=device-width, initial-scale=1">
	<meta name="format-detection" content="telephone-no">

	<!-- CSS files -->

	<link rel="stylesheet" href="{% static 'css/plugins.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
   

</head>
<body>
<!--preloading-->
<div id="preloader">
    <a class="logo" src="{% static 'images/logo_home2.png' %}"  width="119" height="58">
    <div id="status">
        <span></span>
        <span></span>
    </div>
</div>

<!--end of preloading-->
<!-- BEGIN | Header -->

<header class="ht-header">
	<div class="container">
		<nav class="navbar navbar-default navbar-custom">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header logo">
				    <div class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					    <div id="nav-icon1">
							<span></span>
							<span></span>
							<span></span>
						</div>
				    </div>
				    <a href="{% url 'phim:home'%}"><img class="logo" src="{% static 'images/logo_home2.png' %}"  width="90" height="45"></a>
			    </div>
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse flex-parent" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav flex-child-menu menu-left">
						<li class="hidden">
							<a href="#page-top"></a>
						</li>
						<li class="dropdown first">
							<a class="btn btn-default dropdown-toggle lv1" href="{% url 'phim:home'%}" >
							Trang chủ <i aria-hidden="true"></i>
							</a>
							<!-- <ul class="dropdown-menu level1">
								<li><a href="#">1</a></li>
								<li><a href="#">2</a></li>
								
							</ul> -->
						</li>
						<li class="dropdown first">
							<a class="btn btn-default dropdown-toggle lv1"  data-hover="dropdown">
							Khám phá<i class="fa fa-angle-down" aria-hidden="true"></i>
							</a>
							<ul class="dropdown-menu level1">
								<li class="dropdown">
									<a class="dropdown-toggle" href="{% url 'phim:movie' %}"  >Xem phim<i ></i></a>
									
								</li>			
								<li><a href="{% url 'phim:movie' %}">Thể loại</a></li>
								<li><a href="moviesingle.html">Bộ sưu tập</a></li>
	
							</ul>
						</li>
						<li class="dropdown first">
							<a class="btn btn-default dropdown-toggle lv1" href="{% url 'phim:film' %}">
							Phim lẻ <i  aria-hidden="true"></i>
							</a>
						</li>
						<li class="dropdown first">
							<a class="btn btn-default dropdown-toggle lv1" href="{% url 'phim:series' %}" >
							Phim bộ <i  aria-hidden="true"></i>
							</a>
							
						</li>
						<li class="dropdown first">
							<a class="btn btn-default dropdown-toggle lv1" href="{% url 'phim:actor' %}">
							Phim hot <i  aria-hidden="true"></i>
							</a>
						</li>
						<li class="dropdown first">
							<a class="btn btn-default dropdown-toggle lv1" href="{% url 'phim:actor' %}">
							Diễn viên <i  aria-hidden="true"></i>
							</a>
						</li>
				
					</ul>
					<ul class="nav navbar-nav flex-child-menu menu-right">
						<!-- <li class="dropdown first">
							<a class="btn btn-default dropdown-toggle lv1" data-toggle="dropdown" data-hover="dropdown">
							pages <i class="fa fa-angle-down" aria-hidden="true"></i>
							</a>
							<ul class="dropdown-menu level1">
								<li><a href="landing.html">Landing</a></li>
								<li><a href="404.html">404 Page</a></li>
								<li class="it-last"><a href="comingsoon.html">Coming soon</a></li>
							</ul>
						</li>                
						<li><a href="#">Help</a></li> -->
						{% if request.user.is_authenticated %}
						<li><a href="{% url 'phim:logout' %}">Đăng xuất</a></li>
						<li style="    background-color: #dd003f;
						color: #ffffff;
						padding: 5px 25px;
						-webkit-border-radius: 20px;
						-moz-border-radius: 20px;
						border-radius: 20px;"><a href="{% url 'phim:user_profile' %}">{{ user }}</a></li>

						{% else %}
						<li><a href="{% url 'phim:login' %}">Đăng nhập</a></li>
						<li style="    background-color: #dd003f;
						color: #ffffff;
						padding: 5px 25px;
						-webkit-border-radius: 20px;
						-moz-border-radius: 20px;
						border-radius: 20px;"><a href="{% url 'phim:register' %}">Đăng kí</a></li>
						{% endif %}
					</ul>
				</div>
			<!-- /.navbar-collapse -->
	    </nav>
	    
	    <!-- top search form -->\
	
		<form method="get" action="{% url 'phim:search' %}" >
	 	   <div class="top-search">
			
	    		<select name="category">
					<option value="">Tất cả</option>
					{% for category in categories %}
					<option value="{{ category.slug }}" >{{ category.name }}</option>
					{% endfor %}
				</select>
				<select name="tags">
					<option value="">Thể loại</option>
					{% for tag in tags %}
						<option value="{{ tag.slug }}">{{ tag.name }}</option>
					{% endfor %}
				</select>
				<select name="release_year">
					<option value="">Năm</option>
					{% for year in release_years %}
						<option value="{{ year }}">{{ year }}</option>
					{% endfor %}
				</select>
				<select name="country">
					<option value="">Quốc gia</option>
					{% for country in countries %}
					<option value="{{ country.country }}">{{ country.country }} ({{ country.count }})</option>
					{% endfor %}
				</select>
				<button class = "done-search" type="submit">
					Tìm 
				</button>
	    	</div>
		</form>
	</div>
</header>
<!-- END | Header -->


{% block content %}
{% endblock content %}

<!-- footer section-->
<footer class="ht-footer" >
	<div class="container">
		<div class="flex-parent-ft">
			<div class="flex-child-ft item1">
				 <a href="{% url 'phim:home'%}"><img class="logo" src="{% static 'images/logo_home3.png' %}" alt=""></a>
				 <p>5th Avenue st, manhattan<br>
				New York, NY 10001</p>
				<p>Call us: <a href="#">(+01) 202 342 6789</a></p>
			</div>
			<div class="flex-child-ft item2">
				<h4>Resources</h4>
				<ul>
					<li><a href="#">About</a></li> 
					<li><a href="#">Blockbuster</a></li>
					<li><a href="#">Contact Us</a></li>
					<li><a href="#">Forums</a></li>
					<li><a href="#">Blog</a></li>
					<li><a href="#">Help Center</a></li>
				</ul>
			</div>
			<div class="flex-child-ft item3">
				<h4>Legal</h4>
				<ul>
					<li><a href="#">Terms of Use</a></li> 
					<li><a href="#">Privacy Policy</a></li>	
					<li><a href="#">Security</a></li>
				</ul>
			</div>
			<div class="flex-child-ft item4">
				<h4>Account</h4>
				<ul>
					<li><a href="#">My Account</a></li> 
					<li><a href="#">Watchlist</a></li>	
					<li><a href="#">Collections</a></li>
					<li><a href="#">User Guide</a></li>
				</ul>
			</div>
			<div class="flex-child-ft item5">
				<h4>Newsletter</h4>
				<p>Subscribe to our newsletter system now <br> to get latest news from us.</p>
				<form action="#">
					<input type="text" placeholder="Enter your email...">
				</form>
				<a href="#" class="btn">Subscribe now <i class="ion-ios-arrow-forward"></i></a>
			</div>
		</div>
	</div>
	<div class="ft-copyright">
		<div class="ft-left">
			<p><a target="_blank" href="https://www.templateshub.net">Templates Hub</a></p>
		</div>
		<div class="backtotop">
			<p><a href="#" id="back-to-top">Back to top  <i class="ion-ios-arrow-thin-up"></i></a></p>
		</div>
	</div>
</footer>
<!-- end of footer section-->

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/plugins.js' %}"></script>
<script src="{% static 'js/plugins2.js' %}"></script>
<script src="{% static 'js/custom1.js' %}"></script>
</body>


</html>